### ISSUE TITLE
frontend for gov module

### ISSUE THREAD

**Issue by xmonader** [threefoldtecharchive/threefold_hub#14]

**Comment by OmarElawady** [comment]
Frontend added with the following pages:
1. Adding a new text proposal (system upgrade proposals are not added yet)
![image](https://user-images.githubusercontent.com/13040543/162012303-a9634811-1bde-483c-9522-0cd553a672d4.png)

2.Llisting proposals
![image](https://user-images.githubusercontent.com/13040543/162012667-f146cde6-6514-4500-a6e1-c536bcc5ffc9.png)

3. Voting on a proposal (in the voting stage)
![image](https://user-images.githubusercontent.com/13040543/162012728-54cb7b7f-23bd-4e0a-bf52-10b095706477.png)

4. Depositing on a proposal (in the deposit stage)
![image](https://user-images.githubusercontent.com/13040543/162012846-a321e8b0-17c6-4519-b5f6-16f6a3a70861.png)

Notes:
- The proposal wasn't finalized except after the voting period ended (configured here as 1 min for testing purposes). The default is 2 days and on cosmos hub its 14. This means if we use this as the update procedure, the update will take days before committing.

**Comment by OmarElawady** [comment]
TODO:
1. address validation (and other input validation) before submitting
2. keplr installed check revisit (keplr is injected to `window` at the end of loading, need to check how to start operations depending on it after it's injected)
3. automatic gas calculations 
4. wait until transaction is confirmed before reporting `send to cosmos` success. If it can take long we can check for ~5 seconds and then print the transaction hash aferwards.
