### ISSUE TITLE
prepare flist for deploying threefold hub/validators

### ISSUE THREAD

**Issue by xmonader** [threefoldtecharchive/threefold_hub#16]
- need to exist as docker image
- convert to flist 
- document the environment variables

**Comment by ashraffouda** [comment]
https://github.com/threefoldtech/threefold_hub/pull/40

**Comment by xmonader** [comment]
@ashraffouda what is the flist url?

**Comment by ashraffouda** [comment]
https://hub.grid.tf/ashraf.3bot/ashraffouda-threefold_hub-latest.flist

**Comment by xmonader** [comment]
thanks. will close as it should be also autobuilt in the workflow #70
