### ISSUE TITLE
tendermint / cosmos research (URGENT)

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/threefold_hub#2]
## idea

- deploy a cosmos blockchain in test/research mode

## requirements

- integration & tested with keplr
- see how to enabled in keplr app (portal web based)
- allow people to vote & create proposals (using keplr app/portal)
- multisign to create tokens & send them to accounts of people
- create currency (document), called TFGOV = governance token
- integrate vlang workers (see #3)

## deliverables

- docker build script to build container (based on ubuntu 20.04)
- terraform script how to deploy a development instance of cosmos + tendermint + ...
- info/tutorials how to do things in cosmos, links to info/manuals
- document how voting can be done
- allow everyone to experiment with cosmos on top of TFGrid and create own DAO & Digital Currency

## remarks

- use cosmos sdk (golang)

## questions

- can more than 1 currency be supported on 1 chain?

**Comment by abom** [comment]
I'm still exploring the ability to have a bridge for cosmos modules to V via RMB.

**Comment by ashraffouda** [comment]
Was investigating running a blockchain with cosmos sdk
It works and was able to do some transactions
Now still exploring creating apps

**Comment by xmonader** [comment]
for keplr wallet to work with non native chain, seems there's an experimental feature to `suggest a chain` https://docs.keplr.app/api/suggest-chain.html . I didn't find a way for having that to work with keplr "portal"

also in the provided vue application you can do 
![image](https://user-images.githubusercontent.com/64129/154313553-00ecbf3d-2964-4e87-9f19-256034936404.png)


Also from the provided vue you should be able to connect your custom chain to cosmos hub 
![image](https://user-images.githubusercontent.com/64129/154314489-7fc81e70-2db6-4164-a116-aa6f702d12be.png)

But didn't manage to do it.


For the question of is it possible to have multiple coins on the same chain, the answer seems to be yes https://github.com/cosmos/cosmos-sdk/blob/master/types/coin.go#L160

![image](https://user-images.githubusercontent.com/64129/154315275-e32e12da-77bf-4804-a5c4-3b015920e663.png)

**Comment by ashraffouda** [comment]
was checking adding kvstore with cosmos-sdk and starport added a code for this here https://github.com/threefoldtech/research/tree/development/cosmoskv
still investingating how to add a custom store

**Comment by xmonader** [comment]
https://github.com/threefoldtech/threefold_hub/tree/development/research
