### ISSUE TITLE
Document transaction fees

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtecharchive/threefold_hub#21]
- [ ] How much
- [ ] What happens to them? Are they burned/sent to the validator or a predefined address?

**Comment by OmarElawady** [comment]
Added information about it in https://github.com/threefoldtech/threefold_hub/pull/24. If the amount to be specified is the same, we can do uatom->usd->tft conversion.

**Comment by robvanmieghem** [comment]
please add an example how much a transfer costs in tft

**Comment by OmarElawady** [comment]
For a transfer on a cosmos test chain I deployed. The gas used for the transaction is `61886`. The TFTs corresponding to .025uatom (the gas price in cosmos hub) is approximately 8e-6 TFTs. So the transfer fees would be  `61886 * 8e-6 = .5` TFT.

The `min-gas-price` can be tuned per-validator to increase/decrease the paid fees.

**Comment by OmarElawady** [comment]
When the `min-gas-price` was set to 8e-6, the gravity orchestrator required 2 TFTs to do operations on threefold hub.

**Comment by xmonader** [comment]
@OmarElawady if we have that documented please close the issue
