### ISSUE TITLE
Create a testnet genesis config

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtecharchive/threefold_hub#26]

**Comment by OmarElawady** [comment]
Made with BSC BUSDs instead of TFTs. If there's a TFT contract on testnet, it should be easy to reconfigure.
https://github.com/threefoldtech/threefold_hub/pull/33

**Comment by xmonader** [comment]
can be safely closed now https://github.com/threefoldtech/threefold_hub/tree/development/docs/deployment

**Comment by robvanmieghem** [comment]
where is the testnet genesis ?
