### ISSUE TITLE
Add a development genesis file

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtecharchive/threefold_hub#27]

**Comment by OmarElawady** [comment]
What is the difference between this and the testnet chain?

**Comment by robvanmieghem** [comment]
The testnet chain is  long running and available to the public, this one would be for development purposes ( getting a new chain up for a single developer).

**Comment by xmonader** [comment]
this can be safely closed now https://github.com/threefoldtech/threefold_hub/tree/development/docs/deployment
