### ISSUE TITLE
Why is there a stake token and what is it?

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtecharchive/threefold_hub#28]
in the readme/Get started, some of the commands to configure the chain are:

```
threefold_hubd add-genesis-account alice 200000000stake,10000TFT --keyring-backend=test
threefold_hubd gentx --moniker test-node alice 100000000stake 0xD6DBC796aC81DC34bDe3864f1F2c8f40742D85Dc <alice-address> --chain-id=threefold-hub --keyring-backend=test
```

What is the stake token and why is it there?

**Comment by OmarElawady** [comment]
I wasn't sure initially whether the TFT token coming from Binance would be the default token in the chain used for staking. So another token was added for staking and TFT was a BSC-originating token and wasn't used anywhere in staking/minting/... As it'll be used as the default token it's removed here
https://github.com/threefoldtech/threefold_hub/pull/34

**Comment by robvanmieghem** [comment]
at first sight, stake is still present or referenced in
`app/build/env.list.example`
`config.yml`
