### ISSUE TITLE
Change the testnet bridge from BUSD to TFT

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtecharchive/threefold_hub#37]

**Comment by robvanmieghem** [comment]
blocked on:
[Testnet TFT is out of our control](https://github.com/threefoldfoundation/tft/issues/148)

**Comment by OmarElawady** [comment]
Changed in https://github.com/threefoldtech/threefold_hub/pull/41

**Comment by xmonader** [comment]
verified
