### ISSUE TITLE
tutorial basics for money chain

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/threefold_hub#4]
lets document all the basics for how to deal with a cosmos blockchain for digital money creation

lets document following in this repo

- [x] how to deploy cosmos chain for 1 node https://github.com/threefoldtech/research/tree/development/cosmosresearch#running-chain
- [x] how to create a currency on it e.g. FTF, with initial parameters what are these parameters https://github.com/threefoldtech/research/tree/development/cosmosresearch#configuring-tokens
- [ ] how to deploy easiest possible client (TS) 
    - [ ] provide install script (npm ...)
- [x] how to mint money (TS api?), futher creation of money (after initial deployment)  https://github.com/threefoldtech/research/tree/development/cosmosresearch#minting-tokens-at-runtime, https://github.com/threefoldtech/research/tree/development/cosmosresearch#configuring-inflation
- [ ] how to create account (TS api) https://github.com/threefoldtech/research/tree/development/cosmosresearch#make-the-key-available-as-account
- [x] how to send money from one account to other (TS api) https://github.com/threefoldtech/research/tree/development/cosmosresearch#sending-money-bank  https://github.com/threefoldtech/research/tree/development/cosmoskv/chain_client 
- [ ] how to do multisignature using a javascript api on an account (like in stellar) before money can be send (TS api)
- [ ] how to connect kepler mobile to it, show how money can be send

provide TS example wherever relevant

**Comment by ashraffouda** [comment]
added some [docs](https://github.com/threefoldtech/threefold_hub/tree/development-cosmos-docs/docs/cosmos) for how to start the chain and running the vuejs UI
added a [type script client](https://github.com/threefoldtech/research/tree/development/cosmoskv/chain_client) doing token transfere from one account to another

**Comment by xmonader** [comment]
should be obsolete now
