### ISSUE TITLE
What kind of BSC nodes should be used?

### ISSUE THREAD

**Issue by OmarElawady** [threefoldtecharchive/threefold_hub#42]
Options:
- light node
- full node
- third party node

We tried a light node and `https://data-seed-prebsc-2-s1.binance.org:8545/` from this [list](https://docs.binance.org/smart-chain/developer/rpc.html) of rpc endpoints on testnet. And both worked without issues. Syncing a light client took a couple of hours. Using a 3rd party node trusts it completely and assumes the information returned from it is correct [in a non-cryptographically-proven manner](https://www.parity.io/blog/what-is-a-light-client/).

**Comment by robvanmieghem** [comment]
I suggest using a light node

**Comment by xmonader** [comment]
ops are using light node in their testnet deploymnet (also seems there was a ratelimit with 3rdparty nodes https://github.com/threefoldtech/tf_operations/issues/841)
