### ISSUE TITLE
get started assumes knowledge of a mnemonic

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtecharchive/threefold_hub#45]
line 18 of the main readme.md states
`threefold_hubd keys add alice --keyring-backend test --recover # enter the mnemonics here`

how is one suppose to know the mnemonic? Either put a valid mnemonic in the doc or document creating alice without prior knowledge of a mnemonic

**Comment by OmarElawady** [comment]
Changes were made in genesis and token. The readme is revised to contain the latest changes.
PR: https://github.com/threefoldtech/threefold_hub/pull/47
