### ISSUE TITLE
tutorial basics for creating a voting app

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/threefold_hub#5]
- [ ] how to use the keplr admin webinterface
- [ ] how to host our own version of this webinterface (if possible)
- [x] how to add our token to it (which can be used for voting power)
- [x] how to create a vote
- [x] how to vote

explain what possibilities we have to vote (how does voting work), link to info in manuals

**Comment by xmonader** [comment]
https://github.com/threefoldtech/research/blob/development/poll/docs/tutorial.md

covers how to create a poll + vote + ending poll, sending money to the creator of the poll 
coins used can be changed with by changing this https://github.com/threefoldtech/research/blob/development/poll/x/poll/keeper/msg_server_submit_vote.go#L42

**Comment by xmonader** [comment]
Gaia UI isn't supported anymore, and in the new frontend they don't support the governance. it's not included, it will require either them updating  or us going with a custom made solution
