### ISSUE TITLE
missing clear documentaion for how to setup hub 

### ISSUE THREAD

**Issue by hossnys** [threefoldtecharchive/threefold_hub#53]
- [x] missing prerequisites for installation (startport , go , gcc ).
- [x] missing from where to start the process .
- [x] missing the amount of gov min_deposit is the minimum amount for a proposal to be put to a vote .
- [x] missing the crisis constant fee.
- [x] missing how to get BSC-delegator-address  (that's the address of the owner of the validator node -can be retrieved from metamask-)
- [ ] will add  every missing part come along with the setup process

**Comment by xmonader** [comment]
aggregated info here https://github.com/threefoldtech/threefold_hub/blob/development/opsguide.md

**Comment by xmonader** [comment]
@hossnys given that you deployed testnet. i'll close this issue.
