### ISSUE TITLE
TFT in docs or markdown is multiplied by 10000000

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtecharchive/threefold_hub#59]
Since TFT has 7 decimals, 1 TFT in config is 10000000TFT but in docs or in markdown explaining values, this should not be stated as 10000000TFT but as 1TFT

**Comment by OmarElawady** [comment]
Updated in https://github.com/threefoldtech/threefold_hub/pull/61/ and https://github.com/threefoldtech/threefold_hub/commit/d6528503a917fc386d6cad34afc6c8a55f9fef94
