### ISSUE TITLE
Threefold Hub input validation

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtecharchive/threefold_hub#71]
Tested on https://threefoldhub.test.gridtesting.xyz/ 

Currently there is barely any input validation in [Threefold Hub](https://threefoldhub.test.gridtesting.xyz/).

Validation needs to be added to certain fields, real-time error messages should be added. Submit buttons should be disabled when the input is incorrect, and error messages should be clear and user friendly.

The fields that needs validation are: 

### Send to Cosmos

In the send to Cosmos page there are 2 fields:

- Amount field: Needs to only accept non-negative numeric values (Currently accepts anything) and needs validation for insufficient balance (If possible).

- Destination field: Needs validation for the correct address format.

### Send to BSC

In the send to BSC page there are 2 fields:

- Amount field: Needs to only accept non-negative numeric values (Currently accepts anything) and needs validation for insufficient balance (If possible).

- Destination field: Needs validation for the correct address format.

### Add Proposals

In the Add Proposal page there are 3 fields:

- Title field: Should have validation for Title format and for min and max length. 

- Initial Deposit field: Needs to only accept non-negative numeric values (Currently accepts anything) and needs validation for insufficient balance (If possible), and empty field validation.

- Description field: Should have validation for min length and max length (if there is any). 

### Delegate Validators

In the Delegate Validators page there is 1 field:

- Amount field: Needs to only accept non-negative numeric values (Currently accepts anything) and needs validation for insufficient balance (If possible), and empty field validation.

### Error messages 

The error messages available now are not clear or user friendly.

![image](https://user-images.githubusercontent.com/101194226/165274484-7bcc5c80-6062-4067-afce-296f8ee1914a.png)

![image](https://user-images.githubusercontent.com/101194226/165274632-08de7141-869d-4fb8-bf78-872857a5a097.png)

![image](https://user-images.githubusercontent.com/101194226/165275214-bd34d42a-fa2f-40b7-aefd-b14ee0ed759c.png)

**Comment by OmarElawady** [comment]
The input validation is enhanced in https://github.com/threefoldtech/threefold_hub/pull/73, and deployed on https://threefoldhub.test.gridtesting.xyz/. Can you please check and report if you have any comments?

**Comment by mohamedamer453** [comment]
### Send to Threefold Hub

- **Amount Field:** Validation was added but the error messages should be improved.
For example: 
Empty filed error message should be `Min allowed amount is 1` or `Field Can't be Empty`

   ![image](https://user-images.githubusercontent.com/101194226/169295136-e65b4556-69a2-457c-9ef2-e098e46bcd2f.png)

   The field shouldn't allow anything other than numeric values or the message for non-numeric values should be improved.

   ![image](https://user-images.githubusercontent.com/101194226/169295844-69c75d6c-e430-4335-b8d3-a2dc55ab7508.png)

    also the validation for insufficient balance was not added. `and needs validation for insufficient balance (If possible).`

    ![image](https://user-images.githubusercontent.com/101194226/169296467-5e846983-c9ec-47dc-8606-bb6dd81badc6.png)

- **Destination Field**
    Validation for the Destination Field was added But the message could be improved.
     `Invalid Threefold Hub Address` instead of `Not a valid Threefold Hub`


### Send to BSC

- **Amount Field:** Validation was added but the same error messages as mentioned above can be improved.
  
     Validation for insufficient funds was added but the `Send` button is not disabled and the error message needs to be simplified. 

   ![image](https://user-images.githubusercontent.com/101194226/169302993-ab9aeebb-ebc1-4889-a67f-b2fa9c909e67.png)


- **Destination Field:** Also the message Could be improved.
   `Invalid BSC Address` instead of `address length must be 42`


### Add Proposals

- **Title:** Only validation when the field is empty was added but it doesn't disable the `Submit` Button.

  ![image](https://user-images.githubusercontent.com/101194226/169298782-e359f298-20e3-48a5-bd59-4a48a5d9caf7.png)

  Validation for min/max length was not added also validation for special characters was not added.

- **Initial Deposit:** Same issue as mentioned in the `Amount` Field Above, the error messages needs to be improved and  also the `Submit` button should be disabled.
- **Description:** The `Submit` should be disabled when the field is empty and min/max validation was not added (I'm not sure if it should be added or not but i think at least a reasonable max length should be added to prevent further issues)

### Delegate Validators

- **Amount:**  Similar issue to the `Amount` fields mentioned above, the messages should be improved.


### Error Messages

The error messages are still not clear or user friendly enough.

![image](https://user-images.githubusercontent.com/101194226/169301858-dd194829-a724-4cd1-8e35-aabf23f7a4b2.png)

**Comment by mohamedamer453** [comment]
Validation for the new `Add Software Proposal` tab should be added.

### Title

- Empty Field validation.
- Min/Max length.
- Special characters/spaces (If needed).

### Description

- Empty Field validation.
- Min/Max length (If needed).

### Name

- Empty Field validation.
- Min/Max length.
- Special characters/spaces (If needed).

### Initial Deposit
- Empty Field validation.
- Validation for non-negative numeric values. 
- Validation for insufficient balance (If possible).

### Height

- Empty Field Validation.
- Should accept only numeric values (Currently accepts Special characters like: `+`, `-` and letters like `e` )

### Operating Systems

- Empty field validation
- URL Format Validation
- Validation for `OS`, `Arch` if not selected

also the `+` and `-` icons are overlapping

![image](https://user-images.githubusercontent.com/101194226/169308160-9af0cc21-9ffd-4d43-bd64-06d1870d2053.png)

**Comment by OmarElawady** [comment]
Amount can be a fraction (e.g. 1.123), so it's not limited to digits only. Other fixes added in https://github.com/threefoldtech/threefold_hub/pull/87

**Comment by mohamedamer453** [comment]
## Send to Threefold Hub

### Amount

Validation was added and Error messages were improved.

- Empty Field

   ![image](https://user-images.githubusercontent.com/101194226/174572891-8dbdc685-d096-4c6f-aa6d-76e6278a93f3.png)

- Spaces

   ![image](https://user-images.githubusercontent.com/101194226/174573118-63500b0b-6b31-4b5c-83c3-56308bf3cdc7.png)

- Letters

   ![image](https://user-images.githubusercontent.com/101194226/174573203-0d05e0a2-65b7-48c4-8e36-c728ff23933b.png)

- Negative Values

   ![image](https://user-images.githubusercontent.com/101194226/174573261-ca9d3d15-7cd5-4ef0-be67-ed09ce4892f0.png)

- Special Characters 

   ![image](https://user-images.githubusercontent.com/101194226/174573364-098b5d14-1034-4f5a-82e9-4d3792c7aa88.png)

- The only Allowed Special character is `.` since the amount can be a fraction

   ![image](https://user-images.githubusercontent.com/101194226/174573570-2a59ce04-3814-4b5a-bb68-0946fdc0b61d.png)


- Validation for insufficient balance was added after you click the `Send` Button,

   ![image](https://user-images.githubusercontent.com/101194226/174573951-473cf4fd-1b1a-4776-9541-c568cdf64cba.png)


### Destination

Validation was added and Error messages were improved.

- Empty Field

   ![image](https://user-images.githubusercontent.com/101194226/174574390-958def28-c861-4170-bd94-bcaf47d0ebbb.png)

- Invalid Address

   ![image](https://user-images.githubusercontent.com/101194226/174574537-940a1c43-2e55-43b5-ad77-e6a59b62db53.png)




## Send to BSC

### Amount

All validations are working and error messages are available except for the ones mentioned in the comment above. they were not fixed.

- Empty Field

   The error message is still `amount must be positive` when the field is left empty while it should be `Amount is required` like the one available in `Send to Threefold Hub`

   ![image](https://user-images.githubusercontent.com/101194226/174583514-d989fae7-cb27-4610-8d31-33dd670ff62a.png)


- Validation for insufficient balance.

   The message for insufficient balance wasn't changed and still needs improvement. and the `Send` button is not disabled when the balance is insufficient.

   ![image](https://user-images.githubusercontent.com/101194226/174585681-f12e6c22-6a1b-44c9-a0e1-5e7878da2356.png)



### Destination

Validation was added and Error messages were improved.


- Invalid Address

   The error message for empty field and invalid address still needs improvement.

   ![image](https://user-images.githubusercontent.com/101194226/174586817-2653308e-ba41-43a6-a671-0ad5d6b37785.png)


## Add Text Proposal

### Title

- Empty Field

  The only working validation for this field and now it disables the `Submit` Button.

   ![image](https://user-images.githubusercontent.com/101194226/174588065-44d11b5f-6b5c-43b8-bf12-9acf4bae4e88.png)


- Other validations (Ignore if they're not needed)

   All other validation are not available for this field (Min/Max Length, Spaces, Special Characters, etc...)

   ![image](https://user-images.githubusercontent.com/101194226/174587642-8b4dd7a6-2861-4932-b19e-3f3a14c4d119.png)

### Initial Deposit

- Empty field

    The `Submit` button is now disabled when there's an error with the field but the error messages was not improved and it still needs to be changed from `amount must be positive` to `Amount is required` 

     ![image](https://user-images.githubusercontent.com/101194226/174589421-a61c0e22-8f34-4057-bf75-cf2d20c13466.png)

- Validation for insufficient balance was added.

   ![image](https://user-images.githubusercontent.com/101194226/174590123-8a8206c6-9a81-490e-a133-53c4a703f003.png)


### Description

- Empty Field

   The `Submit` button is now disabled when the field is empty.

    ![image](https://user-images.githubusercontent.com/101194226/174590719-b7bc98ab-aeb1-448a-9c33-4a939aafed31.png)

- Max Length (Ignore if not needed)

   Validation for max length was not added.

## Add Software Proposal

### Title

- Empty field
   
   Empty field validation was added and it disables the `Submit` Button

   ![image](https://user-images.githubusercontent.com/101194226/174594259-25cb329f-8d50-4cf9-8fec-41561ad321bc.png)

- Other validations (Ignore if they're not needed)

   All other validation are not available for this field (Min/Max Length, Spaces, Special Characters, etc...)

   ![image](https://user-images.githubusercontent.com/101194226/174594426-0cfe1761-7482-4a54-a4ec-a9e449294ac8.png)


### Description

- Empty field
   
   Empty field validation was added and it disables the `Submit` Button

    ![image](https://user-images.githubusercontent.com/101194226/174594521-48edc3c1-aaa9-4857-9379-0f1b68634be6.png)

- Max Length (Ignore if not needed)

   Validation for max length was not added.


### Name

- Empty field
   
   Empty field validation was added and it disables the `Submit` Button

    ![image](https://user-images.githubusercontent.com/101194226/174594769-eb7de02b-152a-43f0-b074-e1e14648ca89.png)

- Other validations (Ignore if they're not needed)

   All other validation are not available for this field (Min/Max Length, Spaces, Special Characters, etc...)

    ![image](https://user-images.githubusercontent.com/101194226/174594977-b16e325a-b590-4f83-ad01-ca58303f2bb2.png)

### Initial Deposit

- Same issue with the amount field in `Send to BSC` and `Add Proposal` all validations and error messages are added and working except for the validation message for empty field it still needs to be changed.

   ![image](https://user-images.githubusercontent.com/101194226/174595204-94111f5f-d37c-4c22-bc93-a21762eb6121.png)

- Insufficient Balance Validation

  Insufficient balance validation wasn't added to this field.

### Height

- Empty field
   
   Empty field validation was added and it disables the `Submit` Button

   ![image](https://user-images.githubusercontent.com/101194226/174595787-7cbb1428-d023-4f63-9acb-d361e3f2dd8a.png)

- Min height

   Min height validation was added and it disables the `Submit` Button

   ![image](https://user-images.githubusercontent.com/101194226/174595867-34120411-cf47-4fe6-af05-9d4dba5c7a39.png)

- Max height (Ignore if not needed)

   No validation for max height was added.

   ![image](https://user-images.githubusercontent.com/101194226/174596220-086fd6b5-12bc-465b-83a3-a9e70eab6ef4.png)

- Special characters

   Validation for special characters needs to be added since this is a numeric only field and it currently accepts values like `+`, `-`, `e`, `.` (ignore the `.` if decimal values are allowed)

   ![image](https://user-images.githubusercontent.com/101194226/174596740-016b1b37-db56-4b1d-8188-9d01c5f60f5e.png)

   ![image](https://user-images.githubusercontent.com/101194226/174596790-2285b14e-f755-4c99-ad61-4a4a89a5cfba.png)

   ![image](https://user-images.githubusercontent.com/101194226/174597024-4a1aa95a-7def-4767-b00f-43a21ab1929a.png)

   ![image](https://user-images.githubusercontent.com/101194226/174596962-c117aa6b-d7d2-4b18-b97f-6ccd2b20786a.png)


### URL

- Empty field
   
   Empty field validation was added and it disables the `Submit` Button

   ![image](https://user-images.githubusercontent.com/101194226/174597523-e44fa07d-7076-4927-86c3-3f70b4c2b116.png)

- URL Format

   URL Format Validation was added but the validation message need to be simplified like `Invalid URL` instead of `invalid url: TypeError: Failed to construct 'URL': Invalid URL`

   ![image](https://user-images.githubusercontent.com/101194226/174597661-b4be4314-b214-4b6b-9e29-55de8cc2f5a4.png)

   The URL validation is passed after adding `http://` and then anything after that. is this enough for this field or should it be more strict ? 

   ![image](https://user-images.githubusercontent.com/101194226/174597967-104d00d7-0b47-45af-804d-86572539c673.png)


## Delegate Validators

### Amount

- Same issue with the amount field in `Send to BSC` and `Add Proposal` all validations and error messages are added and working except for the validation message for empty field it still needs to be changed.

   ![image](https://user-images.githubusercontent.com/101194226/174593614-ae1599b0-4e9f-47aa-9540-7f4f541a923c.png)


- Validation for insufficient balance was added.

    ![image](https://user-images.githubusercontent.com/101194226/174593487-f47ac097-abfe-4aea-87fc-44e4a5265fb2.png)

**Comment by mohamedamer453** [comment]
so in summery, what needs to be checked

## Send to BSC

### Amount Field

- The error message is still `amount must be positive` when the field is left empty while it should be `Amount is required` like the one available in `Send to Threefold Hub`

- Validation for insufficient balance message needs to be improved.

   ![image](https://user-images.githubusercontent.com/101194226/174604569-79393f68-8f27-4f85-b07a-32d206a3dcb8.png)


### Destination Field

- The error message for empty field and invalid address still needs improvement. like `Invalid Address` when the field is empty instead of `address length must be 42`.

**Comment by mohamedamer453** [comment]
## Add Text Proposal 

### Title Field 


The only validation working for this field is the empty field validation and there are no other validations like (Min/Max Length, Spaces, Special Characters, etc...)   (Ignore these validations if they're not needed)

### Initial Deposit

- The error message is still `amount must be positive` when the field is left empty while it should be `Amount is required` like the one available in `Send to Threefold Hub`

### Description

- Max length validation was not added. (Ignore if it's not needed)

**Comment by mohamedamer453** [comment]
## Add Software Proposal 

### Title Field 

- The only validation working for this field is the empty field validation and there are no other validations like (Min/Max Length, Spaces, Special Characters, etc...)   (Ignore these validations if they're not needed)

### Description

- Max length validation was not added. (Ignore if it's not needed)

### Name Field 

- The only validation working for this field is the empty field validation and there are no other validations like (Min/Max Length, Spaces, Special Characters, etc...)   (Ignore these validations if they're not needed)

### Initial Deposit

- The error message is still `amount must be positive` when the field is left empty while it should be `Amount is required` like the one available in `Send to Threefold Hub`

- Insufficient balance validation wasn't added to this field.


### Height

- Max height (Ignore if not needed)

   No validation for max height was added.

   ![image](https://user-images.githubusercontent.com/101194226/174596220-086fd6b5-12bc-465b-83a3-a9e70eab6ef4.png)

- Special characters

   Validation for special characters needs to be added since this is a numeric only field and it currently accepts values like `+`, `-`, `e`, `.` (ignore the `.` if decimal values are allowed)

   ![image](https://user-images.githubusercontent.com/101194226/174596740-016b1b37-db56-4b1d-8188-9d01c5f60f5e.png)

   ![image](https://user-images.githubusercontent.com/101194226/174596790-2285b14e-f755-4c99-ad61-4a4a89a5cfba.png)

   ![image](https://user-images.githubusercontent.com/101194226/174597024-4a1aa95a-7def-4767-b00f-43a21ab1929a.png)

   ![image](https://user-images.githubusercontent.com/101194226/174596962-c117aa6b-d7d2-4b18-b97f-6ccd2b20786a.png)


### URL


- URL Format

   URL Format Validation was added but the validation message need to be simplified like `Invalid URL` instead of `invalid url: TypeError: Failed to construct 'URL': Invalid URL`

   The URL validation is passed after adding `http://` and then anything after that. is this enough for this field or should it be more strict ? 

   ![image](https://user-images.githubusercontent.com/101194226/174597967-104d00d7-0b47-45af-804d-86572539c673.png)

**Comment by mohamedamer453** [comment]
## Delegate Validators

### Amount

- The error message is still `amount must be positive` when the field is left empty while it should be `Amount is required` like the one available in `Send to Threefold Hub`

**Comment by mohamedamer453** [comment]
Verified on https://tfhub.test.grid.tf

## Send to BSC

### Amount 

- The error message for the empty field was changed from `amount must be positive` to `Amount is required`

   ![image](https://user-images.githubusercontent.com/101194226/174983079-4df128a6-6942-4bd8-9ffa-ad9ec20501da.png)

- Validation message for insufficient balance was improved.

   ![image](https://user-images.githubusercontent.com/101194226/174983227-52a1d236-b083-4612-8379-da7e24a790af.png)


### Destination

- The error message for empty field was changed from `address length must be 42` to `Address must be non-empty`

   ![image](https://user-images.githubusercontent.com/101194226/174983574-6c149cdb-1174-46d1-988c-3a6bd9be23e2.png)




## Add Text Proposal

### Title (Ignored)

- The mentioned validations were not needed.

### Initial Deposit

- The error message for the empty field was changed from `amount must be positive` to `Amount is required`

   ![image](https://user-images.githubusercontent.com/101194226/174984095-d11b157a-e1f1-41f7-9a0a-2d7b7772d925.png)

### Description (Ignored)

- Max length is not needed for this field.


## Add Software Proposal

### Title (Ignored)

- The mentioned validations were not needed.

### Description (Ignored)

- Max length is not needed for this field.

### Name (Ignored)

- The mentioned validations were not needed.

### Initial Deposit

- The error message for the empty field was changed from `amount must be positive` to `Amount is required`

   ![image](https://user-images.githubusercontent.com/101194226/174984095-d11b157a-e1f1-41f7-9a0a-2d7b7772d925.png)

### Height

- Max length (Ignored)
   - Max length is not needed for this field.

- Special Characters
   - This field only accepts numeric values now and the user can't enter any of the mentioned characters `+`, `-`, `e`, `.` 

### URL

- The validation message for invalid url format was changed from `invalid url: TypeError: Failed to construct 'URL': Invalid URL` to `Invalid url`

   ![image](https://user-images.githubusercontent.com/101194226/174986362-f2b35d6e-35d0-41b1-85b6-367135265c4d.png)


## Delegate Validators

- The error message for the empty field was changed from `amount must be positive` to `Amount is required`

   ![image](https://user-images.githubusercontent.com/101194226/174983079-4df128a6-6942-4bd8-9ffa-ad9ec20501da.png)

**Comment by mohamedamer453** [comment]
The only issue left is in the `Height` field in `Add Software Proposal`.

The field accepts any amount of zeros before the actual value without producing any errors.

![image](https://user-images.githubusercontent.com/101194226/174989139-38a11fd0-285e-4607-88e7-12addcb1f6ce.png)


- Suggestion

The same validation that was added to the `Height` field in `Add Software Proposal` should be added to the `Amount`/`Initial Deposit` fields available throughout Threefold Hub  (I'm not entirely sure if it's applicable or not since the Amount can be a decimal value)

**Comment by OmarElawady** [comment]
Yeah, because 0123123 is a valid integer, so it's not an error to use it as an input. Same can't be done for Amount and Initial deposit since they can be decimal as you indicated.

**Comment by mohamedamer453** [comment]
Closing since all the issues were resolved
