### ISSUE TITLE
TC569 - Sending from BSC to Cosmos

### ISSUE THREAD

**Issue by dmitri-alleo** [threefoldtecharchive/threefold_hub#85]
Sending from BSC to Cosmos (ThreeFold Hub)

When trying to approve the transaction on MetaMask, getting this error

![image](https://user-images.githubusercontent.com/65153287/174029341-c659df76-9112-473a-b03f-50eabbb1f443.png)

URL: https://tfhub.test.grid.tf/
Env: Testnet

**Comment by OmarElawady** [comment]
What is the account address of the Binance account you used for sending the tokens. Making sure it's a "not enough funds" error.

**Comment by xmonader** [comment]
closed for inactivity
